### PR TITLE
Proxy plausible analytics - fixes #1625

### LINKED ISSUE #1625: Suggestion: Proxy Plausible Events
We are likely losing analytics data due to visitors using ad / tracker blockers.

It is possible to [proxy events to plausible analytics](https://plausible.io/docs/proxy/introduction) via a proxy on the site's domain. They have a guide [specifically for vercel](https://plausible.io/docs/proxy/guides/vercel) as well.

### PR DESCRIPTION
**Pull request by w3cj**
This fix proxies analytic events through the site's domain so they are not blocked by ad blockers / trackers.

### CODE REVIEW

**Comment by wesbos** [comment]
Looks like it's still being blocked, likely because it has /stats/ in the url? Do we have control over what the URL is?  

Screenshot 2024-03-28 at 4 44 33 PM

**Comment by wesbos** [comment]
Yeah it is. I think you should be able to just re-name the re-write and the data-api something like `/static/appz/elelphant`

Screenshot 2024-03-28 at 4 54 50 PM

**Comment by w3cj** [comment]
Updated the path and seems to work now.

**Comment by wesbos** [comment]
confirmed its not being blocked. Merging

**Pull request merged**
