### PR TITLE
Create 751 - UI Components.md

### PR DESCRIPTION
**Pull request by randyrektor**

### CODE REVIEW

**Comment by randyrektor** [comment]
Wondering if these keep failing because YouTube automatically makes a video 'Private' when it's scheduled. I wonder if I left it 'Unlisted' if there would be no playback problem? @stolinski

**Comment by w3cj** [comment]
It failed to fetch one of the costco links. Wonder if this was just a temporary flub. Re-running to see.

**Comment by randyrektor** [comment]
Oh interesting! Thanks @w3cj

**Comment by w3cj** [comment]
This URL just hangs for an HTTP/1.1 HEAD request: https://www.costco.ca/ontel-battery-daddy-180-battery-organizer-and-storage-case-with-tester.product.4000032542.html

You can replicate with CURL: `curl -v -I --http1.1 https://www.costco.ca/ontel-battery-daddy-180-battery-organizer-and-storage-case-with-tester.product.4000032542.html`

Really weird behavior for their server.

We probably just need to add a timeout to the URL checking and fail any URL that takes longer than X seconds to resolve.

**Pull request merged**
