### PR TITLE
Update to npm-run-all2

### PR DESCRIPTION
**Pull request by bcomnes**
[`npm-run-all2`](https://github.com/bcomnes/npm-run-all2) is a community fork of [`npm-run-all`](https://github.com/mysticatea/npm-run-all), which sadly hasn't had updates for over 5 years. 

I started the fork because I use `run-{p,s}` everywhere and wanted to see its ongoing maintenance continued. We're at 40k public repos adopting the fork so far, and are a designated replacement package in renovate bot. The plan for the fork is to keep maintaining the project pretty much as is for the foreseeable future. 

I'm sending out a few PRs to notable repos that I spot to see gauge interest on switching over.

It's a drop in replacement (same bin names) so this should be all you need to do to switch over. 

Love the podcast! Feel free to close if you aren't interested as well.

### CODE REVIEW

**Review by stolinski — APPROVED** [review]

**Comment by stolinski** [comment]
This looks great,  thank you.

**Comment by bcomnes** [comment]
I can't see why the website build failed, but if you need a hand with that related to this change, let me know.

**Comment by wesbos** [comment]
annoying pnpm package lock issue.. should have approved it to run first before merging

**Comment by wesbos** [comment]
fixed!

**Pull request merged**
