### PR TITLE
Create 809 - DailyDev

### PR DESCRIPTION
**Pull request by stolinski**

### CODE REVIEW

**Comment by dually8** [comment]
I don't know if it's just me, but this isn't showing up on the main site. It might have something to do with this not having the `.md` extension. I noticed all of the other ones in this folder are markdown files.

**Comment by wesbos** [comment]
@dually8 thank you → https://github.com/syntaxfm/website/commit/56cf60afd71bf5beae760410241d8b6e7f5ac572

**Comment by dually8** [comment]
Sure thing! Love the podcast and the site! Thanks for all you do!

**Comment by stolinski** [comment]
That was my fault. 😞. It passed the markdown checker though 😅😅😅

Scott Tolinski

www.scotttolinski.com ( http://www.scotttolinski.com/ )

**Pull request merged**
