### PR TITLE
Add hotkeys to the audio player

### LINKED ISSUE #1195: Player needs a way to be opened after it's been closed
right now if you close the player, it keeps playing, but there isn't a way to get it back open unless you click play on the audio again.

Would be nice for it to minimize into just the show title / 1 line high

### PR DESCRIPTION
**Pull request by RatulMaharaj**
This PR Implements hotkeys to control the audio player via the keyboard.  

|Hotkey| Description|
|:---:|:---|
|`i`| Toggle player visibility (currently only if a show is loaded)|
|`m`|Toggle the player mute state|
|`Space`| Pause / Play audio|
|`j`|Seek backward 30s|
|`l`|Seek forward 30s|
|`<`|Increase playback rate|
|`>`|Decrease playback rate|
|`?`|Show hotkey help|

> **Note**
> The above is largely influenced by [Youtube's player shortcuts](https://support.google.com/youtube/answer/7631406?hl=en). I also considered the [Spotify shortcuts](https://support.spotify.com/us/article/keyboard-shortcuts/).

I don't have strong opinions about what the actual keys used should be, so if anyone else does, happy for it to be changed. 

Related to #1195 

## Updates

1. Stopping audio and removing show on player close.

2.  Implemented a `MINIMIZED` version of the player

image

3. Added `?` hotkey to the above

4. Added a global hotkey `?` / `shift+/` to bring up the list of hotkeys.

image

### CODE REVIEW

**Comment by RatulMaharaj** [comment]
@wesbos this should be ready for review now.

**Comment by wesbos** [comment]
thanks a ton - will review shortly

**Comment by themisterholliday** [comment]
This should also fix: https://github.com/syntaxfm/website/issues/1338

**Comment by stolinski** [comment]
Love the menu here. @wesbos would you mind if I were to merge this into my embed branch instead of main and merge with the work i'm doing? 
Reason being is I've made a number of changes to the player itself so merging into main might put us in a conflict

**Comment by stolinski** [comment]
Hey @RatulMaharaj this is awesome however since it conflicts with some design changes I've made in a branch, I'm going to merge it there instead of main and massage the merge a bit. 

Thank you, this is great!

**Pull request merged**
